### ISSUE TITLE
Correct way to use xip.io?

### ISSUE THREAD

**Issue by kculmback** [JPry/vvv-base#30]
Simply put, I have not been able to get xip.io to work. 

Whenever I attempt to go to the website (somewebsite.0.0.0.0.xip.io; using my IP address), I get an error saying the DNS address cannot be found. 

If I do the same thing but use nip.io instead, I get the VVV2 dashboard. 

I also followed some of the steps listed at this gist to no avail:
https://gist.github.com/jubstuff/4cc9eff7fa919af9a21b

Is there anything I'm missing or do you have any suggestions? Any help would be greatly appreciated!

**Comment by JPry** [comment]
Hi @kculmback,

I wrote an article a while ago about how to use Xip.io. I saw that it needed some updates, and the latest version is here: https://jeremypry.com/how-to-view-a-locally-developed-website-on-other-devices/.

That should give you what you need to get started.

**Comment by JPry** [comment]
Hi @kculmback,

If you need any further assistance, please feel free to reach out. I'm going to go ahead and close this issue, but discussion can continue if needed.
