### ISSUE TITLE
Add support for Certificate Authority (tls-ca)

### ISSUE THREAD

**Issue by jancbeck** [JPry/vvv-base#35]
VVV v.2.2.1 came with support for HTTPS:
https://varyingvagrantvagrants.org/docs/en-US/references/https/

The changes to the custom-site-template were minimal, but I had no luck implementing them into a PR for vvv-base:
https://github.com/Varying-Vagrant-Vagrants/custom-site-template/commit/98d37a85d03fdacdf9fcbfed395cbf3302426df8

**Comment by JPry** [comment]
@jancbeck Thanks for bringing this to my attention. It looks like something that should be doable with `vvv-base`.
