### ISSUE TITLE
Not adding the hosts option after provisioning

### ISSUE THREAD

**Issue by thomasdot** [JPry/vvv-base#38]
I've followed the bare minimum guidelines (i.e. simply adding the repo to vvv-custom.yml, but the URL isn't being generated. Do I still have to do this, despite the guidance?

**Comment by JPry** [comment]
@thomasdot Thanks for reaching out. Could you clarify what you mean by the URL not being generated? Where are you looking for it to be generated but not seeing it?

If you're able to share your `vvv-custom.yml` file, as well as the provision command you're running, that would be helpful.
