### ISSUE TITLE
'Skipping' over default themes for deletion

### ISSUE THREAD

**Issue by thomasdot** [JPry/vvv-base#39]
If I use `delete_default_themes`, but want to keep select themes installed, what should I do? I've tried simply setting the relevant option (i.e. `theme: -twentyseventeen`), but `delete_default_themes` always works after this process.

**Comment by JPry** [comment]
I think this would be a matter of just changing the order of content when provisioning here: 

https://github.com/JPry/vvv-base/blob/47244bf46d80baf88151c0bdcb2a729cf3dd0213/src/Provisioner.php#L113-L118

`deleteDefaultContent()` could be moved before `installPlugins()` and `installThemes()`.
